name: hearing_hands
description: A new Flutter project.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  shared_preferences: ^2.3.5
  smooth_page_indicator: ^1.1.0
  youtube_player_flutter: ^9.1.3
  flutter_inappwebview: ^6.0.0
  firebase_core: ^3.10.1
  firebase_auth: ^5.4.1
  cloud_firestore: ^5.6.1
  confetti: ^0.8.0
  image_picker: ^1.2.1
  firebase_storage: ^12.4.10

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1 

flutter:
  uses-material-design: true
  assets:
    - assets/images/hhlogo.png
    - assets/images/logo.png
    - assets/images/group.jpg
    - assets/images/talk.png
    - assets/images/bear.png
    - assets/images/welcome.png
    - assets/images/google.png
    - assets/images/c_a.png
    - assets/images/c_b.png
    - assets/images/c_c.png
    - assets/images/c_d.png
    - assets/images/c_e.png
    - assets/images/c_f.png
    - assets/images/c_g.png
    - assets/images/abclesson.png
    - assets/images/deflesson.png
    - assets/images/ghilesson.png
    - assets/images/jkllesson.png
    - assets/images/mnolesson.png
    - assets/images/pqrlesson.png
    - assets/images/stulesson.png
    - assets/images/vwxlesson.png
    - assets/images/yzlesson.png
    - assets/images/profile.jpg
    - assets/images/fire.png
    - assets/images/calendar.png
    - assets/images/groupbear.png
    - assets/images/talkbear.png
    - assets/images/talkbearr.png
    - assets/images/splash.png
    - assets/images/awards/alphabetace.png
    - assets/images/awards/dictionaryexplorer.png
    - assets/images/awards/feelingsfriend.png
    - assets/images/awards/fivedaychamp.png
    - assets/images/awards/greetingsguru.png
    - assets/images/awards/lessonmaster.png
    - assets/images/awards/luckyseven.png
    - assets/images/awards/numberninja.png
    - assets/images/awards/quicklearner.png
    - assets/images/awards/quizrookie.png
    - assets/images/awards/quizwhiz.png
    - assets/images/awards/trailblazer.png
    - assets/images/awards/triplethreat.png
    - assets/images/awards/twodaychamp.png
    - assets/images/awards/twoweekstreaker.png
    - assets/images/celebration.png
    - assets/images/celebrationn.png
    - assets/images/locked.png
    - assets/images/dictionary/
    - assets/images/avatar/
    - assets/images/games/

  fonts:
    - family: Whisper
      fonts:
        - asset: assets/fonts/Whisper-Regular.ttf

    - family: VarelaRound
      fonts:
        - asset: assets/fonts/VarelaRound-Regular.ttf
